USE `erp_wci`;
/*-- ESTADOS --*/
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (1,'Acre','AC',' 12',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (2,'Alagoas','AL',' 27',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (3,'Amazonas','AM',' 13',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (4,'Amapá','AP',' 16',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (5,'Bahia','BA',' 29',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (6,'Ceará','CE',' 23',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (7,'Distrito Federal','DF',' 53',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (8,'Espírito Santo','ES',' 32',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (9,'Goiás','GO',' 52',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (10,'Maranhão','MA',' 21',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (11,'Minas Gerais','MG',' 31',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (12,'Mato Grosso do Sul','MS',' 50',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (13,'Mato Grosso','MT',' 51',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (14,'Pará','PA',' 15',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (15,'Paraíba','PB',' 25',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (16,'Pernambuco','PE',' 26',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (17,'Piauí','PI',' 22',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (18,'Paraná','PR',' 41',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (19,'Rio de Janeiro','RJ',' 33',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (20,'Rio Grande do Norte','RN',' 24',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (21,'Rondônia','RO',' 11',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (22,'Roraima','RR',' 14',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (23,'Rio Grande do Sul','RS',' 43',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (24,'Santa Catarina','SC',' 42',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (25,'Sergipe','SE',' 28',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (26,'São Paulo','SP',' 35',1,1,1,CURDATE(),CURDATE());
INSERT INTO `States`(`StateId`,`Name`,`FederativeUnit`,`ExternalCode`,`Active`,`UserID`,`UserIDLastUpdate`,`CreateDate`,`ModifieldDate`) VALUES (27,'Tocantins','TO',' 17',1,1,1,CURDATE(),CURDATE());
